### PR TITLE
It's GitHub, not Github

### PR DESCRIPTION
**Pull request by brntbeer**
Not really sure how `index.html` is being created, but it had a lower-case **h** in GitHub. this fixes that terrible atrocity. 

(lololol :heart: I'm more than happy to fix this in the correct way, just let me know!)

### CODE REVIEW

**Comment by jxnblk** [comment]
The company's name is the atrocity :)

http://mobile.nytimes.com/2009/11/29/magazine/29FOB-onlanguage-t.html?referrer=&_r=0

**Comment by brntbeer** [comment]
So is this a "wont fix" or is there something i can do to help get this fixed?

**Comment by jxnblk** [comment]
If you wanna fix it, this would be the place to adjust: https://github.com/jxnblk/jxnblk.github.io/blob/master/src/data.js

Then `npm i` and `npm run prod` to rebuild.

**Comment by brntbeer** [comment]
You da best. gimmie a min and i'll getcha

**Comment by brntbeer** [comment]
@jxnblk if you want me to rebase and squash all of this into a single commit let me know (especially those last two commits).

Also, i noticed `node_modules/` isn't in the gitignnore, and after `npm i` it creates that. Think that should be added too?

**Comment by jxnblk** [comment]
Yeah, I keep that in my global gitignore, but you can add it to this repo if that helps.

Also, don't worry about squashing – I like history :)

**Pull request closed without merging**
